name: crawller_backend
version: 0.4.0
description: Dart Functions Framework simple function example.
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.2
  path_provider: ^2.0.10
  functions_framework: ^0.4.1
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  puppeteer: ^2.9.0
  logger: ^1.1.0
  uuid: ^3.0.6
  hive: ^2.2.1
  firedart:
    git:
      url: https://github.com/dev-tryit/firedart.git
      ref: addXFirebaseLocaleHeader # branch name


dev_dependencies:
  build_runner: ^2.1.11
  functions_framework_builder: ^0.4.6
  http: ^0.13.4
  test: ^1.21.1
  test_process: ^2.0.2
